import Head from 'next/head'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bootstrap Next App</title>
        <meta name="description" content="Generated by Bootstrap Next App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="row mt-4">
        <Card />
        <Card />
        <Card />
        <Card />
      </div>
      <div className="row mt-4">
        <Card />
        <Card />
        <Card />
        <Card />
      </div>
      
    </div>
  )
}
